# in a production environment, 'secret.yaml' is not to be pushed to a git repository, etc.
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: Auth123
  JWT_SECRET: some_secret_secret
type: Opaque