apiVersion: v1
kind: Service
metadata:
  name: auth  # name of the overall service
spec:
  selector:
    app: auth
    type: ClusterIP  # IP address assigned to that service is only accessible within the cluster
    ports:
      - port: 5000
        targetPort: 5000
        protocol: TCP